version: '3.7'

services: 
  salt-master:
    build:
      context: .
      dockerfile: config/Dockerfile.salt-master
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ${PWD}/srv:/srv
  salt-minion:
    build:
      context: .
      dockerfile: config/Dockerfile.salt-minion
    environment:
      - MINION_NAME=minion
      - LOG_LEVEL=debug
    depends_on:
      - salt-master
