FROM ubuntu:22.04

COPY config/install_salt.sh /usr/bin/install_salt.sh
RUN sh /usr/bin/install_salt.sh -M

RUN sed -i 's/#auto_accept: False/auto_accept: True/g' /etc/salt/master
COPY config/start_master.sh /usr/bin/start_master.sh

ENTRYPOINT ["./usr/bin/start_master.sh"]
